name: GladePvP
version: ${project.version}
main: com.thegladenetwork.gladepvp.GladePvP
api-version: 1.13
authors: [JezCam, Amaterasu]
description: Custom PvP plugin for The Glade Minecraft server
website: thegladeserver.com
